version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      ## APP_HOST: sparkles-hello-world_server_1
      ## APP_PORT: 3000
      APP_HOST: konna-neo4j_1
      APP_PORT: 7474
    
  server:
    ## image: getumbrel/community-app-store-hello-world:latest
    ## user: "1000:1000"
    ## init: true
    image: neo4j:5.26.12-ubi9
    user: "1000:1000"
    init: true
    environment:
      - NEO4J_AUTH=neo4j/${APP_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/logs:/logs
      - ${APP_DATA_DIR}/import:/var/lib/neo4j/import
      - ${APP_DATA_DIR}/plugins:/plugins
    
